name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  extension_ci:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Setup Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install Node Dependencies
        run: yarn

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: espressif/idf-web-ide:latest